### ISSUE TITLE
Toggle line comment not working

### ISSUE THREAD

**Issue by nachocab** [pouyakary/nearley-vscode#1]
Great job on the extension!

Unfortunately I can't get the Toggle Line Comment command to work. It works on other languages, but not on nearley, for some reason.

I tried adding a `language-configuration.json` file with this (also because selecting a character and pressing `"` overwrites it instead of surrounding it), but it didn't work:

```
{
  "comments": {
    "lineComment": "!"
  },
  "brackets": [["{", "}"], ["[", "]"], ["(", ")"]],
  "autoClosingPairs": [["{", "}"], ["[", "]"], ["(", ")"], ["\"", "\""], ["`", "`"]],
  "surroundingPairs": [["{", "}"], ["[", "]"], ["(", ")"], ["\"", "\""], ["`", "`"]]
}
```
Do you have any ideas?

**Comment by pouyakary** [comment]
Hi @nachocab 

I'll make an update soon and this will be fixed. Thanks a lot for using it :D

**Comment by nachocab** [comment]
Excellent! Let me know if you need any help. 

I haven't been able to find the reason, but I'm assuming there is a simple setting that lets you enable comment toggling and also selecting a piece of code, hitting the `(` key, for example, and surrounding it (instead of deleting the selection as is currently the case). 

Also, it doesn't seem to be specific to the nearley syntax because it also happens inside the JS postprocessor tags (inline `{% %}` and block `@{% %}`)

**Comment by nachocab** [comment]
Great, thanks! Now you just have to publish the update 😊
