### ISSUE TITLE
Nested macroses wrong syntax highlighting

### ISSUE THREAD

**Issue by valyakin** [pouyakary/nearley-vscode#4]
Hi!
Thank you for your great work!
I want to report a bug related to nested macroses syntax highlighting
Sample grammar:

```
macro1[X] -> $X
macro2[Y] -> $Y

main -> macro1[("aaa" | macro2["bbb"] | "ccc")]
```

expected behavior: in `main` everything before last ']' highlighted with red

current behavior:
![image](https://user-images.githubusercontent.com/32761513/61139020-f403d700-a4e1-11e9-8c3f-57732d70515d.png)

**Comment by thislooksfun** [comment]
This happens whenever there is a `]` anywhere within the macro. Namely `macro["]"]` is also parsed incorrectly.

**Comment by pouyakary** [comment]
Hi @valyakin and @thislooksfun :*
Very embarrassingly I didn't know about macros and their grammar 🙃
I'm a little bit busy right now, but I hope that I can mange to fix it in the coming weeks. 

Till then :*
